// basic consistent layut between pages,, children are the diff pages
import { Metadata} from "next";

export const metadata : Metadata= {
    title: {
      absolute: "",
      default: "Next.js Tutorial - Codevolution",
      template: "%s | Codevolution",
    },
    description: 'Generated by Next.js',
  }

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body>
          <header
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              padding: '10px 20px',
              backgroundColor: '#f5f5f5',
            }}>

            <p>Header</p>
          </header>

          {children}
          


          <footer
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              padding: '10px 20px',
              backgroundColor: '#f5f5f5',
            }}>
            <p>Footer</p>
          </footer>
          
          </body>
      </html>
    )
  }  